name = "smartprojectmanager"
pages_build_output_dir = "dist"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "smartprojectmanager-db"
database_id = "891c6520-2f2d-4c33-8bf2-05627b85de7e"
